Add
FlexConfirmMail/Outlook-Office-Addin pull request #18
Opened 2024-10-04 08:57 UTC by HashidaTKS

![image](https://github.com/user-attachments/assets/b4efba69-64c1-4def-89ee-fe8cfa4b996a)

2024-10-04 09:13 UTC, piroor commented on src/web/app.js
>  function onMessageSend(event) {
こちらの関数名が古いようです。mainへのrebaseし忘れでしょうか？

2024-10-04 09:13 UTC, HashidaTKS commented on src/web/app.js
>  function onMessageSend(event) {
すみません、色々途中の状態です。Draftにします。

2024-10-04 09:14 UTC, piroor commented on src/web/app.js
> +  getAllData(async function () {
こちらはPromiseベースになる前の設計のままのようです。
mainとconflictしませんか？

2024-10-04 09:16 UTC, piroor commented
すみません、作業中でまだレビューは早かったのですね。失礼しました！

2024-10-04 10:10 UTC, HashidaTKS commented
@piroor 

すみません、レビュー可能な状態になりました。レビューをお願いします。

2024-10-04 10:31 UTC, piroor commented on src/web/app.js
> +  const [to, cc, bcc, mailId] = await Promise.all([getToAsync(), getCcAsync(), getBccAsync(), getMailIdAsync()]);
だいぶ右に長くなっているので、右辺はgetAllDataと同様に改行するようにしたほうがよさそうです。

2024-10-04 10:38 UTC, piroor commented on src/web/dialog.js
> +function appendNewlyAddedDomain(data) {
このappendXXXXという名前は、この確認ダイアログ自体の文脈に基づくappendCheckboxesなどの名前付けを引き継いだ物だと思うのですが、今回追加する物はそれとは文脈が違うサブダイアログになるので、サブダイアログ用の初期化関数が親ダイアログ用の初期化関数と同じレベルの名前付けになっているのは、混乱の元になりそうな気がします。

サブダイアログの管理用オブジェクトのようなものを用意して、

```javascript
const AddedDomainsReconfirmation = {
  init(data) { ... },
  show() { ... },
};
```

のようにするのはどうでしょうか？

2024-10-04 10:40 UTC, piroor requested changes
今後の拡張性、メンテナンス性の観点からコメントしました

2024-10-07 01:39 UTC, HashidaTKS reviewed
@piroor 

レビューありがとうございます。
指摘事項に対応しました。

2024-10-07 01:39 UTC, HashidaTKS commented on src/web/dialog.js
> +function appendNewlyAddedDomain(data) {
classに分離しました。

2024-10-07 01:39 UTC, HashidaTKS commented on src/web/app.js
> +  const [to, cc, bcc, mailId] = await Promise.all([getToAsync(), getCcAsync(), getBccAsync(), getMailIdAsync()]);
改行しました。

2024-10-07 01:59 UTC, piroor approved these changes
Looks good to merge.

2024-10-07 02:00 UTC, merged

2024-10-07 02:00 UTC, piroor commented
Thanks!